config/routes.rb
Rails.application.routes.draw do
    devise_for :users, controllers: {
    registrations: 'user/registrations'
  }
    #HOME PAGE
    root to: "pages#index"
    get '/', to: 'pages#index', as: 'homepage'
    get '/about', to: 'pages#about', as: 'about'
    get '/option', to: 'pages#option', as: 'option'
    get '/profile/:id', to: 'pages#profile', as: 'profile'
  

    #ITEMS
    #show list
    get '/items', to: 'items#dashboard', as: 'items'
    #always put an ailas as: on a get method

    #show all items for sale
    get 'items/all', to: 'items#index', as: 'all_items'
 

    #Create items
    get '/items/new', to: 'items#new', as: 'new_item'
    post '/items', to: 'items#create'
    
    #Read items
    get '/items/:id', to: 'items#show', as: 'item'

    #add item to wishlist
    get "/items/:id/add", to: "items#add", as: "add_item_to_list"

    #remove item from wishlist
    get "/items/:id/remove", to: "items#remove", as: "remove_item_from_list"
    
    #Edit items
    get '/items/:id/edit', to: 'items#edit', as: 'edit_item'
    
    #Update items
    patch '/items/:id', to: 'items#update'
    put '/items/:id', to: 'items#update'
 
    #Delete items
    delete '/items/:id', to: 'items#destroy', as: 'destroy_item'

  #ORDER
  #Show my logs
  get "/mylist", to: "orders#index", as: "orders"
  
  get '/orders/new', to: "orders#new", as: "new_order"
  
  get '/orders/complete', to: "orders#complete", as: "completed_order"
  post "/orders/webhook", to: "orders#webhook"
  
  get 'orders/receipt/:id', to: "orders#receipt", as: "purchase_receipt"



  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  belongs_to :item

#method for checking if the item already exists in user's list

  def self.contains?(current_user, item)
  return current_user.items.where(id: item).length > 0
  
  
  end
  
  
  
  
  # def self.previous_orders(user)
  #   orders = Order.where(user_id: user).reverse_order
  # end

  # # gets the information of a purchased item
  # def self.purchased_item(item_id)
  #   order = Order.where(item_id: item_id)
  # end



end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  skip_before_action :verify_authenticity_token, only: [:webhook]


    def index
      @wishlists = current_user.wishlists
      @orders = current_user.orders
    end

     
    def new
      @item = Item.find(params[:item_id])
      @session = Stripe::Checkout::Session.create(
      payment_method_types: ['card'],
      line_items: [{ 
        name: @item.name,
        description: "from #{@item.category}",
        # images: ["#{@item.picture.service_url if @item.picture.attached?}"],
        amount: (@item.price * 100).to_i,
        currency: 'aud',
        quantity: 1,
      }],
      payment_intent_data: {
        metadata: {
          user_id: current_user.id,
          item_id: @item.id
        }
      },
      success_url: "#{root_url}orders/complete",
      cancel_url: "#{root_url}",
      )
    end


    def complete
    @items = current_user.items
    end
  
    def webhook
      payment_id = params[:data][:object][:payment_intent]
      payment = Stripe::PaymentIntent.retrieve(payment_id)
      item_id = payment.metadata.item_id
      user_id = payment.metadata.user_id
      p "item id #{item_id}"
      p "user id #{user_id}"
      
      @orders = Order.new
      @orders.user_id = user_id
      @orders.item_id = item_id
      @orders.save
      
      @item = Item.find(item_id)
      @item.sold = true
      @item.save
      render plain: "Success"

    end



 

end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/orders/complete.html.erb
<h1>Thank you for purchasing</h1>

<h2 class="title">Order Complete!</h2>


<%= link_to "Go back to Home", items_path%>

app/views/orders/index.html.erb
<h1>My Wishlist</h1>

    <% @wishlists.each do |wishlist|%>
    <% item = Item.find(wishlist.item_id)%>
    <p><%= link_to item.name, item_path(item) %> </p>
  <td><%= image_tag item.picture, class: 'img-thumbnail box', width: 200 if item.picture.attached? %></td>
  
    

<%end%>

<h1>Previous Orders</h1>

    <% @orders.each do |order|%>
    <% item = Item.find(order.item_id)%>
    <p><%= link_to item.name, item_path(item) %> </p>
    <td><%= image_tag item.picture, class: 'img-thumbnail box', width: 200 if item.picture.attached? %></td>
  
    <%= link_to "Search for more beards to buy!!", all_items_path()%>

<%end%>

app/views/orders/new.html.erb
<h1 class="list-item"> Your order
</h1>
<table>
<thead> <tr>
     <th>Name</th>
     <th>Category</th>
     <th>Price</th>
   </tr>
 </thead>
<tbody> <tr>
<td><%= @item.name %></td>
<td><%= @item.category %></td>
<td><%= number_to_currency @item.price %></td>
   </tr>
 </tbody>
</table>


<button id="pay-now">Checkout now</button>

<script src="https://js.stripe.com/v3/"></script>
<script>
 document
   .querySelector("[id='pay-now']")
   .addEventListener("click", () => {
     const stripe = Stripe(
       "<%= Rails.application.credentials.dig(:stripe, :public_key) %>"
     );

     stripe.redirectToCheckout({
       sessionId: "<%= @session.id %>"
     });
   });
</script>