config/routes.rb
Rails.application.routes.draw do
    devise_for :users, controllers: {
    registrations: 'user/registrations'
  }
    #HOME PAGE
    root to: "pages#index"
    get '/', to: 'pages#index', as: 'homepage'
    get '/about', to: 'pages#about', as: 'about'
    get '/option', to: 'pages#option', as: 'option'
    get '/profile/:id', to: 'pages#profile', as: 'profile'
  

    #ITEMS
    #show list
    get '/items', to: 'items#dashboard', as: 'items'
    #always put an ailas as: on a get method

    #show all items for sale
    get 'items/all', to: 'items#index', as: 'all_items'
 

    #Create items
    get '/items/new', to: 'items#new', as: 'new_item'
    post '/items', to: 'items#create'
    
    #Read items
    get '/items/:id', to: 'items#show', as: 'item'

    #add item to wishlist
    get "/items/:id/add", to: "items#add", as: "add_item_to_list"

    #remove item from wishlist
    get "/items/:id/remove", to: "items#remove", as: "remove_item_from_list"
    
    #Edit items
    get '/items/:id/edit', to: 'items#edit', as: 'edit_item'
    
    #Update items
    patch '/items/:id', to: 'items#update'
    put '/items/:id', to: 'items#update'
 
    #Delete items
    delete '/items/:id', to: 'items#destroy', as: 'destroy_item'

  #ORDER
  #Show my logs
  get "/mylist", to: "orders#index", as: "orders"
  
  get '/orders/new', to: "orders#new", as: "new_order"
  
  get '/orders/complete', to: "orders#complete", as: "completed_order"
  post "/orders/webhook", to: "orders#webhook"
  
  get 'orders/receipt/:id', to: "orders#receipt", as: "purchase_receipt"



  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :user
  has_many :orders
  has_many :wishlists
  has_one_attached :picture
  
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController

    def index

        @items = Item.all 
    end
   

    def new
        @items = Item.new
    end


    def dashboard
        @items = current_user.items
     end

    def show
        @items = Item.find(params[:id])
        @can_add = !Order.contains?(current_user, @items) if user_signed_in?
    end

    def add
        @items = Item.find(params[:id])
        #current_user.wishlists.push(@items)
        wishlists = Wishlist.new
        wishlists.user_id = current_user.id
        wishlists.item_id = params[:id]
        if wishlists.save
            flash[:notice] = "Added New Item"
            redirect_to items_path
        else
            flash[:alert] = "Oops! There was a problem adding that Item"
            redirect_back(fallback_location: all_items_path)
        end
    end

    def remove
        @items = Item.find(params[:id])
        current_user.items.destroy(@items)
        flash[:notice] = "Item was removed from your list"
        redirect_to items_path
    end



    def create
      
        @items = Item.new(items_params)
        @items.user_id = current_user.id
        @items.picture.attach(params[:item][:picture])
        @items.sold = false

        if @items.valid? && @items.save
        #if its a post you do a redirect if its a view you do a render
        redirect_to items_path
        else
        render :new

        end
    end 

    def edit
        @items = Item.find(params[:id])
    
    end

    def update
        @items = Item.find(params[:id])

        @items.update!(items_params)
        if @items.valid? && @items.save
            redirect_to items_path
        else
            render :edit
        end
    end

    def destroy
        Item.destroy(params[:id])
        redirect_to items_path
    end

    
    #anything bleow this is private and the user will not see it
    private
    def items_params
    params.require(:item).permit(:name, :category, :colour, :texture, :days_to_cultivate, :price)
    end



end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_form.html.erb
<div> 
<%= form_with model: @items do |form| %>
    <p>
    <%= form.label :name %>
    <%= form.text_field :name %>
    </p>

    <p>
    <%= form.label :category %>
    <%= form.text_field :category %>
    </p>
    
    <p>
    <%= form.label :colour %>
    <%= form.text_field :colour %>
    </p>
    
    <p>    
    <%= form.label :texture %>
    <%= form.text_field :texture %>
    </p>
    
    <p>
    <%= form.label :days_to_cultivate %>
    <%= form.text_field :days_to_cultivate %>
    </p>
    
    <p>
    <%= form.label :price %>
    <%= form.number_field :price, step: '0.01'  %>
    </p>
    
    <p>    
    <%= form.label :picture %>
    <%= form.file_field :picture, accept: "image/png,image/jpeg,image/jpg" %>
    </p>
    
    <p>  
    <%=form.submit "submit"%>
    </p>
    <%end%>
</div>

app/views/items/dashboard.html.erb
<h2>DASHBOARD</h2>

<h4>MY BEARDS CURRENTLY FOR SALE</h4>
<%# loops through and displays all beards currently for sale%>

        <div class ="row-flex">
  <% if @items.length > 0 %>
            <% @items.each do | item | %>
       <div class="item-div">
            <tr>
                <P><%= "#{item.name} #{item.category} " %></P>


                <td><%= link_to image_tag item.picture, class: 'img-thumbnail box', width: 120 if item.picture.attached? %></td>
         
                <p><%= link_to "details", item_path(item.id)%></p>
               <p><%= link_to "edit", edit_item_path(item.id)%></p>
               <p><%= link_to "delete", item, method: :delete, 
              data:{confirm: "Are you sure you want to delete #{item.name}"} %></p>
            </tr>
            </div>            
        <% end %>
    <%else%>
<p>You currently have no beards for sale - perhaps its time for a chop to get some dosh!</p>
<%end%>

       <%#button to upload/sell new beard%>
    </div>
        <div id ="button">
        <a href="/items/new" class="btn btn-dark" role="button">SELL A NEW BEARD!</a>
        </div>
     

app/views/items/edit.html.erb
<h2> Edit Contact </h2>
<%= render "form" %> 

app/views/items/index.html.erb
<h2 class="title has-text-centered">All Items</h2>

<div class ="row-flex">

    <% if @items.length > 0 %>
            <% @items.each do |item| %>
                <div class="item-div">
            

                    <td><%= image_tag item.picture, class: 'img-thumbnail box', width: 237 if item.picture.attached? %></td>
                    <p><%= link_to item.name, item_path(item) %></p>
                    <p>CATEGORY: <%= link_to item.category, item_path(item) %></p>
                    <p>COLOUR: <%= link_to item.colour, item_path(item) %></p>
                    <p>PRICE: <%= number_to_currency(item.price)%></p>
            
                </div>  

            <%end%>
        <%else%>
        <p>Currently no items to display!</p>
    <%end%>
</div>

app/views/items/new.html.erb
<h2> Upload a new Item </h2>
<%= render "form" %> 
<h2><%=link_to 'BACK', :back %></h2>

app/views/items/show.html.erb
<td><%= image_tag @items.picture, class: 'img-thumbnail box', width: 200 if @items.picture.attached? %></td>

<h2><%= "#{@items.name}  #{number_to_currency @items.price}"%></h2>
<% if user_signed_in?%>
    <%if @can_add %>
        <p><%= link_to "Add to my wish list", add_item_to_list_path(@items)%> </p>
    <% else %>
            <% if current_user.id == @items.user.id %>
                    You own this item
            <% else %>
                    <p><%= link_to 'Remove from my wish list', remove_item_from_list_path(@items)%> </p>
            <% end %>
    <% end %>
<% end %>

<p>Email: <%= @items.user.first_name%></p>
<p>Category: <%= @items.category%></p>


<%# Checks if user is signed in, AND item has a price allocated, 
AND the item doesn't belong to the user, AND the item has not been sold,
if so, shows link to buy item %>

<% if user_signed_in?%>
    <% if @items.price %>
    <p>
        <%= number_to_currency @items.price %>
            <% if current_user.id != @items.user.id %>
                You own this item
                <%else%>
                <% if @items.sold == false %>
                   <%= link_to "Buy Now", new_order_path(item_id: @items.id), class: "btn btn-dark"%>
                <%end%>
            <%end%>
    </p>
<% end %>
<% end %>
<% if !user_signed_in?%>
<h2>SIGN IN TO PURCHASE THIS ITEM!</h2>
<% end %>

<%= link_to 'Back', :back %>